#!/bin/bash

IMAGE_PATH="/Volumes/Storage/vm/MountainLion.vmwarevm"
VMWARE_LIBRARY_FOLDER="/Users/swami/Workspace/local/VMWare"
VMRUN=vmrun

if [ "$1" == "start" ]
then
	"$VMWARE_LIBRARY_FOLDER"/"$VMRUN" -T Fusion start "$IMAGE_PATH" nogui
elif [ "$1" == "stop" ]
then
	"$VMWARE_LIBRARY_FOLDER"/"$VMRUN" -T Fusion stop "$IMAGE_PATH"
elif [ "$1" == "list" ]
then
	"$VMWARE_LIBRARY_FOLDER"/"$VMRUN" -T Fusion list
else
	echo "Usage: `basename $0` [start|stop|list]"
fi

